# Server Configuration
server:
  # port: ${PORT:${SERVER_PORT:0}}
  port: 8082

# Spring Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3508/msvc_person?serverTimezone=America/Tegucigalpa&allowPublicRetrieval=false
    username: USER_ADMIN
    password: S3cr3t2023_MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: jdbc.lob.non_contextual_creation=true

  # Application Configuration
  application:
    name: msvc-person

  # Config server
  config:
    import: optional:configserver:http://localhost:8085